### ISSUE TITLE
小白想问下原理

### ISSUE THREAD

**Issue by cyang812** [cyf-gh/ncmdumpHelper#1]
我注意到使用的是 main.exe 进行转换，可是想问下 GUI 程序是如何实现的？ :)

**Comment by cyf-gh** [comment]
使用原作者提供的命令行参数输入，详见 https://github.com/anonymous5l/ncmdump
我调用参数的代码如下。
![image](https://user-images.githubusercontent.com/11147632/75132395-bcb10600-5711-11ea-8177-00cb5ac5f626.png)

fixed
